Repository 13teamProject/Planit, pull requests merged in 2024-07, with the labels that each got.

#69 [#67] 대시보드 관리 - 구성원 삭제 및 페이지네이션 구현
  public/icon/arrow_next.svg
  public/icon/arrow_prev.svg
  src/app/(dashboard)/edit/[id]/page.tsx
  src/app/api/members.ts
  src/components/dashboard/Edit/DashboardMember.tsx
  src/components/dashboard/edits/DashboardMember.tsx
  src/components/dashboard/edits/DashboardName.tsx
Labels: ✨ feat

#70 [#68] 대시보드 - 초대 구현
  @types/dashboard.d.ts
  src/app/(dashboard)/edit/[id]/page.tsx
  src/app/api/dashboards.ts
  src/components/dashboard/edits/DashboardInvitation.tsx
  src/components/dashboard/edits/DashboardMember.tsx
  src/components/dashboard/edits/DashboardName.tsx
  src/constants/globalConstants.ts
  src/utils/validation/schema.ts
Labels: ✨ feat

#81 [#71] 대시보드 관리 - 대시보드 삭제
  @types/commons.d.ts
  src/app/(dashboard)/edit/[id]/page.tsx
  src/components/dashboard/edits/DashboardDeleteButton.tsx
  src/components/dashboard/edits/DashboardInvitation.tsx
  src/components/dashboard/edits/DashboardMember.tsx
Labels: ✨ feat

#84 [#82] 대시보드 관리 / 계정 관리 반응형
  src/components/dashboard/edits/DashboardInvitation.tsx
  src/components/dashboard/edits/DashboardMember.tsx
  src/components/dashboard/edits/DashboardName.tsx
  src/components/mypage/Password.tsx
  src/components/mypage/Profile.tsx
Labels: ♻️ refactor

#87 [#86] Footer 생성
  src/app/page.tsx
  src/components/commons/footer/Footer.tsx
Labels: ✨ feat

#83 [#78] react-toastify 설정, 적용
  @types/cards.d.ts
  package.json
  src/app/layout.tsx
  src/app/test/card/page.tsx
  src/components/commons/input/DateInput.tsx
  src/components/commons/input/ImageInput.tsx
  src/components/commons/input/TagInput.tsx
  src/components/commons/toast/index.tsx
  src/components/dashboard/cards/CreateCardModal.tsx
  src/components/dashboard/cards/EditCardModal.tsx
  src/components/dashboard/columns/CreateColumnModal.tsx
  src/components/dashboard/columns/EditColumnModal.tsx
  src/components/dashboard/todo-detail-card/CardDetails.tsx
  src/styles/react-toastify.css
  yarn.lock
Labels: ✨ feat

#74 [#52]comments
  @types/cards.d.ts
  @types/comments.d.ts
  src/app/api/cards.ts
  src/app/api/comments.ts
  src/app/test/todo-card-test/page.tsx
  src/components/dashboard/todo-detail-card/CardDetails.tsx
  src/components/dashboard/todo-detail-card/CardTitle.tsx
  src/components/dashboard/todo-detail-card/Comment.tsx
  src/components/dashboard/todo-detail-card/CommentInput.tsx
  src/components/dashboard/todo-detail-card/CommentSection.tsx
  src/components/dashboard/todo-detail-card/CommentsList.tsx
  src/components/dashboard/todo-detail-card/DropDownSelectBox.tsx
  src/components/dashboard/todo-detail-card/TodoDetailModal.tsx
  src/components/login/LoginForm.tsx
  src/components/signup/SignUpForm.tsx
  src/hooks/useComment.ts
Labels: ♻️ refactor, ✨ feat

#90 [#89] Tag Color 랜덤 적용
  src/components/commons/input/TagInput.tsx
  src/components/commons/tag/index.tsx
  src/components/dashboard/cards/Card.tsx
  src/components/dashboard/cards/EditCardModal.tsx
  src/utils/color.ts
  tailwind.config.ts
Labels: ✨ feat

#88 [#65]대시보드 초대
  @types/dashboards.d.ts
  src/app/api/dashboards.ts
  src/app/api/inivations.ts
  src/app/mydashboard/page.tsx
  src/components/commons/layout/DashboardHeader.tsx
  src/components/commons/layout/Sidemenu.tsx
  src/components/dashboard/edits/DashboardDeleteButton.tsx
  src/components/mydashboard/InviteDashboard.tsx
  src/components/mydashboard/NewDashboard.tsx
  src/hooks/useInfiniteScroll.ts
Labels: ✨ feat

#91 [#80] 카드 삭제 기능 + 카드 api 리팩토링
  @types/auth.d.ts
  @types/cards.d.ts
  @types/commons.d.ts
  public/image/empty-comment-logo.png
  src/app/api/auth.ts
  src/app/api/cards.ts
  src/app/api/comments.ts
  src/app/api/createRequestWithToken.ts
  src/app/globals.css
  src/app/page.tsx
  src/components/commons/input/Textarea.tsx
  src/components/dashboard/cards/CreateCardModal.tsx
  src/components/dashboard/cards/EditCardModal.tsx
  src/components/dashboard/todo-detail-card/CardDetails.tsx
  src/components/dashboard/todo-detail-card/CommentSection.tsx
  src/components/dashboard/todo-detail-card/DropDownSelectBox.tsx
  src/components/dashboard/todo-detail-card/TodoDetailModal.tsx
  src/components/login/LoginForm.tsx
  src/components/signup/SignUpForm.tsx
  src/components/signup/Terms.tsx
  src/hooks/useComment.ts
  src/hooks/useIntersectionObserver.ts
  src/hooks/useOutsideClick.ts
  src/service/authService.ts
Labels: 🐛 fix, ♻️ refactor, ✨ feat

#96 [#95] 404 페이지 구현
  public/image/error404.png
  src/app/not-found.tsx
Labels: ✨ feat

#99 [#73] 드래그앤 드롭 기능 구현
  src/components/dashboard/cards/Card.tsx
  src/components/dashboard/columns/Column.tsx
Labels: ✨ feat

#94 [#85] Modal -> toast로 변경
  src/components/dashboard/edits/DashboardDeleteButton.tsx
  src/components/dashboard/edits/DashboardInvitation.tsx
  src/components/dashboard/edits/DashboardMember.tsx
  src/components/dashboard/edits/DashboardName.tsx
  src/components/mypage/Password.tsx
  src/components/mypage/Profile.tsx
Labels: ♻️ refactor

#93 [#92] 카드 모달 비활성화 조건 추가
  @types/cards.d.ts
  src/app/test/card/page.tsx
  src/components/commons/button/index.tsx
  src/components/commons/input/DropdownInput.tsx
  src/components/dashboard/cards/CreateCardModal.tsx
  src/components/dashboard/cards/EditCardModal.tsx
  src/components/dashboard/columns/CreateColumnModal.tsx
  src/components/dashboard/columns/EditColumnModal.tsx
  src/components/dashboard/todo-detail-card/CardDetails.tsx
Labels: ♻️ refactor

#97 refactor: 프로젝트 폴더 구조 정리
  @types/cards.d.ts
  @types/columns.d.ts
  @types/comments.d.ts
  @types/commons.d.ts
  @types/dashboard.d.ts
  @types/dashboards.d.ts
  @types/invitations.d.ts
  @types/members.d.ts
  @types/users.ts
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(dashboard)/dashboard/[id]/page.tsx
  src/app/(dashboard)/edit/[id]/layout.tsx
  src/app/(dashboard)/edit/[id]/page.tsx
  src/app/(dashboard)/mydashboard/page.tsx
  src/app/api/cards-goni.ts
  src/app/api/cards.ts
  src/app/api/columns.ts
  src/app/api/dashboards.ts
  src/app/api/getCards.ts
  src/app/api/getColumns.ts
  src/app/api/getDashboardId.ts
  src/app/layout.tsx
  src/app/mypage/layout.tsx
  src/app/mypage/page.tsx
  src/app/page.tsx
  src/app/test/card/page.tsx
  src/app/test/column/page.tsx
  src/app/test/todo-card-test/page.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/SignUpForm.tsx
  src/components/auth/Terms.tsx
  src/components/commons/layout/Sidemenu.tsx
  src/components/dashboard/Card.tsx
  src/components/dashboard/Column.tsx
  src/components/dashboard/ColumnSettingButton.tsx
  src/components/dashboard/CreateCardModal/index.tsx
  src/components/dashboard/modals/CreateCardModal.tsx
  src/components/dashboard/modals/CreateColumnModal.tsx
  src/components/dashboard/modals/EditCardModal.tsx
  src/components/dashboard/modals/EditColumnModal.tsx
  src/components/dashboard/modals/TodoDetailModal/CardDetails.tsx
  src/components/dashboard/modals/TodoDetailModal/Comment.tsx
  src/components/dashboard/modals/TodoDetailModal/CommentSection.tsx
  src/components/dashboard/modals/TodoDetailModal/DropDownSelectBox.tsx
  src/components/dashboard/modals/TodoDetailModal/index.tsx
  src/components/editdashboard/DashboardDeleteButton.tsx
  src/components/editdashboard/DashboardInvitation.tsx
  src/components/editdashboard/DashboardMember.tsx
  src/components/editdashboard/DashboardName.tsx
  src/components/home/Footer.tsx
  src/components/home/Header.tsx
  src/components/mydashboard/NewDashboard.tsx
  src/styles/globals.css
Labels: ♻️ refactor

#103 [#101] dropdown style 변경 / toast 시간 조정
  src/components/commons/input/DropdownInput.tsx
  src/components/commons/toast/index.tsx
  src/components/dashboard/modals/CreateCardModal.tsx
  src/components/dashboard/modals/EditCardModal.tsx
Labels: ♻️ refactor

#105 [#104] 랜덤 Profile Circle 색상
  src/components/commons/circle/ProfileCircle.tsx
  src/components/commons/layout/DashboardHeader.tsx
  src/components/dashboard/modals/CreateCardModal.tsx
  src/components/dashboard/modals/EditCardModal.tsx
  src/components/editdashboard/DashboardMember.tsx
  src/utils/color.ts
  tailwind.config.ts
Labels: ✨ feat

#107 [#106] 스피너 생성 및 적용
  package.json
  src/components/commons/spinner/index.tsx
  src/components/dashboard/modals/TodoDetailModal/CommentSection.tsx
  src/components/dashboard/modals/TodoDetailModal/index.tsx
  yarn.lock
Labels: ✨ feat

#108 [#98] 수정 사항 및 요구 사항 미적용 사항들 적용
  src/app/(dashboard)/edit/[id]/page.tsx
  src/app/page.tsx
  src/components/editdashboard/DashboardDeleteButton.tsx
  src/components/editdashboard/DashboardInvitation.tsx
  src/components/editdashboard/DashboardMember.tsx
  src/components/editdashboard/DashboardName.tsx
  src/components/mypage/Password.tsx
  src/utils/validation/schema.ts
Labels: ♻️ refactor, ✨ feat

#109 [#57] 헤더, 사이드메뉴 수정 및 초대받은 대시보드 수정
  public/icon/sidemenu-toggle.svg
  src/app/(dashboard)/mydashboard/page.tsx
  src/components/commons/layout/DashboardHeader.tsx
  src/components/commons/layout/Sidemenu.tsx
  src/components/mydashboard/InviteDashboard.tsx
  src/components/mydashboard/NewDashboard.tsx
  src/constants/globalConstants.ts
  src/styles/globals.css
  tailwind.config.ts
Labels: ✨ feat

#110 [#100]refactoring
  @types/cards.d.ts
  src/app/api/cards.ts
  src/components/commons/dropdown/index.tsx
  src/components/commons/layout/DashboardHeader.tsx
  src/components/dashboard/modals/EditCardModal.tsx
  src/components/dashboard/modals/TodoDetailModal/CardDetails.tsx
  src/components/dashboard/modals/TodoDetailModal/DropDownSelectBox.tsx
  src/components/dashboard/modals/TodoDetailModal/index.tsx
  src/hooks/useOutsideClick.ts
  src/middleware.ts
Labels: ♻️ refactor, ✨ feat

#118 [#112] dashboardHeader 수정
  src/app/(dashboard)/dashboard/[id]/page.tsx
  src/app/(dashboard)/edit/[id]/layout.tsx
  src/app/mypage/layout.tsx
  src/components/commons/layout/DashboardHeader.tsx
  src/components/editdashboard/DashboardName.tsx
  src/store/dashBoardName.ts
Labels: ♻️ refactor

#113 ✨ feat: animated button 적용
  package.json
  src/app/page.tsx
  yarn.lock
Labels: ✨ feat

#119 [#102] 대시보드 상세화면 모달 연결 및 UI 수정
  src/app/(dashboard)/dashboard/[id]/page.tsx
  src/app/test/card/page.tsx
  src/app/test/column/page.tsx
  src/app/test/todo-card-test/page.tsx
  src/components/dashboard/Card.tsx
  src/components/dashboard/Column.tsx
  src/components/dashboard/ColumnSettingButton.tsx
  src/components/dashboard/modals/EditColumnModal.tsx
  src/components/dashboard/modals/TodoDetailModal/CardDetails.tsx
  src/components/dashboard/modals/TodoDetailModal/index.tsx
Labels: ✨ feat

#117 [#115] 웹소켓을 통한 실시간 통신
  next.config.mjs
  package.json
  src/app/(dashboard)/dashboard/[id]/page.tsx
  src/app/(dashboard)/edit/[id]/layout.tsx
  src/app/(dashboard)/edit/[id]/page.tsx
  src/app/api/dashboards.ts
  src/components/commons/layout/DashboardHeader.tsx
  src/components/commons/toast/index.tsx
  src/components/dashboard/Column.tsx
  src/components/dashboard/modals/CreateCardModal.tsx
  src/components/dashboard/modals/CreateColumnModal.tsx
  src/components/dashboard/modals/EditCardModal.tsx
  src/components/dashboard/modals/EditColumnModal.tsx
  src/components/dashboard/modals/TodoDetailModal/index.tsx
  src/components/editdashboard/DashboardDeleteButton.tsx
  src/components/editdashboard/DashboardName.tsx
  src/pages/api/socket.ts
  src/store/dashBoardName.ts
  src/store/socketStore.ts
  src/styles/react-toastify.css
  yarn.lock
Labels: ✨ feat

#122 [#121] fix: 대시보드 UI 수정 및 카드 수정 렌더링 반영
  src/app/(dashboard)/dashboard/[id]/page.tsx
  src/components/dashboard/Card.tsx
  src/components/dashboard/Column.tsx
  src/components/dashboard/modals/EditCardModal.tsx
  src/components/dashboard/modals/TodoDetailModal/index.tsx
Labels: 🐛 fix

#123 [#114] 사이드메뉴 수정
  package.json
  public/icon/menu-toggle-close.svg
  public/icon/sidemenu-left-black.svg
  public/icon/sidemenu-left.svg
  public/icon/sidemenu-right-black.svg
  public/icon/sidemenu-right.svg
  src/app/api/dashboards.ts
  src/components/commons/layout/DashboardHeader.tsx
  src/components/commons/layout/Sidemenu.tsx
  src/components/mydashboard/NewDashboard.tsx
  yarn.lock
Labels: ✨ feat

#125 [#124] fix: 드래그앤 드롭 수정
  src/components/dashboard/Card.tsx
  src/components/dashboard/Column.tsx
  src/hooks/useDragAndDrop.ts
  src/styles/globals.css
Labels: 🐛 fix

#130 fix: 모달 자잘한 수정
  src/components/commons/circle/ProfileCircle.tsx
  src/components/commons/layout/DashboardHeader.tsx
  src/components/dashboard/Card.tsx
  src/components/dashboard/modals/CreateCardModal.tsx
  src/components/dashboard/modals/CreateColumnModal.tsx
  src/components/dashboard/modals/EditCardModal.tsx
  src/components/dashboard/modals/EditColumnModal.tsx
Labels: 🐛 fix

#131 [#126] 사이드메뉴 디자인 수정
  public/icon/dashboard-pagenation-left-black.svg
  public/icon/dashboard-pagenation-right-black.svg
  public/icon/sidemenu-left-black.svg
  public/icon/sidemenu-left.svg
  public/icon/sidemenu-right-black.svg
  public/icon/sidemenu-right.svg
  src/app/(dashboard)/dashboard/[id]/page.tsx
  src/app/(dashboard)/edit/[id]/layout.tsx
  src/app/(dashboard)/mydashboard/page.tsx
  src/app/mypage/layout.tsx
  src/components/commons/layout/DashboardHeader.tsx
  src/components/commons/layout/Sidemenu.tsx
  src/components/mydashboard/InviteDashboard.tsx
  src/components/mydashboard/NewDashboard.tsx
Labels: ♻️ refactor

#133 Socket.io To Pusher
  package.json
  src/app/(dashboard)/dashboard/[id]/page.tsx
  src/app/(dashboard)/edit/[id]/page.tsx
  src/app/api/cards.ts
  src/app/api/pusher/auth/route.ts
  src/app/api/pusher/cards/emit.ts
  src/app/api/pusher/cards/route.ts
  src/app/api/pusher/columns/emit.ts
  src/app/api/pusher/columns/route.ts
  src/app/api/pusher/dashboards/emit.ts
  src/app/api/pusher/dashboards/route.ts
  src/app/api/pusher/enter/emit.ts
  src/app/api/pusher/enter/route.ts
  src/components/auth/LoginForm.tsx
  src/components/commons/toast/index.tsx
  src/components/dashboard/Column.tsx
  src/components/dashboard/modals/CreateCardModal.tsx
  src/components/dashboard/modals/CreateColumnModal.tsx
  src/components/dashboard/modals/EditCardModal.tsx
  src/components/dashboard/modals/EditColumnModal.tsx
  src/components/dashboard/modals/TodoDetailModal/index.tsx
  src/components/editdashboard/DashboardDeleteButton.tsx
  src/components/editdashboard/DashboardName.tsx
  src/components/mydashboard/InviteDashboard.tsx
  src/hooks/useDragAndDrop.ts
  src/pages/api/socket.ts
  src/store/pusherStore.ts
  src/store/socketStore.ts
  src/styles/react-toastify.css
  src/utils/pusher.ts
  yarn.lock
Labels: ✨ feat

#136 [#135]다크모드 구현으로 인한 버그 픽스
  src/components/auth/LoginForm.tsx
  src/components/auth/SignUpForm.tsx
  src/components/commons/input/index.tsx
  src/components/commons/layout/Sidemenu.tsx
Labels: 🐛 fix

#140 [#139] framer 랜딩 페이지 적용
  src/app/page.tsx
  src/components/commons/animatedContent/index.tsx
  src/components/home/Header.tsx
Labels: ✨ feat
