Repository 13teamProject/Planit, pull requests merged in 2024-06, with the labels that each got.

#10 [#8] tailwind px 설정
  tailwind.config.ts
Labels: 📦 chore

#12 [#11] 아이콘 추가 및 리드미 수정
  README.md
  public/icon/add_box.svg
  public/icon/arrow_drop_down.svg
  public/icon/arrow_forward.svg
  public/icon/calendar.svg
  public/icon/close.svg
  public/icon/crown.svg
  public/icon/envelope_email.svg
  public/icon/facebook.svg
  public/icon/instagram.svg
  public/icon/kebab.svg
  public/icon/search.svg
  public/icon/settings.svg
  public/icon/unsubscribe.svg
  public/icon/visibility_off.svg
  public/icon/visibility_on.svg
Labels: 📦 chore, 📝 docs

#9 Update issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/issue-request.md
Labels: 📦 chore

#6 [#4] 공통 컴포넌트 - Circle
  .eslintrc.json
  package.json
  src/app/layout.tsx
  src/app/test/page.tsx
  src/components/commons/circle/ColorCircle.tsx
  src/components/commons/circle/ProfileCircle.tsx
  yarn.lock
Labels: ✨ feat

#17 [#17] 공통 컴포넌트 - Input
  .eslintrc.json
  package.json
  public/icon/calendar.svg
  public/icon/calendar_gray.svg
  public/icon/plus.svg
  src/app/globals.css
  src/app/input-test/page.tsx
  src/app/test/page.tsx
  src/components/commons/circle/ColorCircle.tsx
  src/components/commons/circle/ProfileCircle.tsx
  src/components/commons/input/DateInput.tsx
  src/components/commons/input/DropdownInput.tsx
  src/components/commons/input/ImageInput.tsx
  src/components/commons/input/TagInput.tsx
  src/components/commons/input/Textarea.tsx
  src/components/commons/input/index.tsx
  src/styles/custom-datepicker.css
  tailwind.config.ts
  yarn.lock
Labels: ✨ feat

#25 [#19] 랜딩페이지 구현
  public/fonts/NEXON_Lv2_Gothic.ttf
  public/fonts/NEXON_Lv2_Gothic_Bold.ttf
  public/fonts/NEXON_Lv2_Gothic_Light.ttf
  public/fonts/NEXON_Lv2_Gothic_Medium.ttf
  public/image/logo_blue.png
  public/image/logo_icon_blue.png
  public/image/logo_icon_white.png
  public/image/logo_text_blue.png
  public/image/logo_text_white.png
  public/image/logo_white.png
  public/image/main_banner.png
  public/image/main_banner_logo.png
  public/image/main_content01.png
  public/image/main_content02.png
  public/image/main_content03_1.png
  public/image/main_content03_2.png
  public/image/main_content03_3.png
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  tailwind.config.ts
Labels: ✨ feat

#24 [#23] Modal 컴포넌트 구현
  src/app/layout.tsx
  src/components/commons/modal/index.tsx
Labels: ✨ feat

#22 [#21] Button Component
  public/icon/add_box_color.svg
  src/components/commons/button/AuthButton.tsx
  src/components/commons/button/BarButton.tsx
  src/components/commons/button/index.tsx
Labels: ✨ feat

#31 [#30] eslint 설정 변경
  .eslintrc.json
  package.json
  src/components/commons/input/DateInput.tsx
  tailwind.config.ts
  yarn.lock
Labels: 🐛 fix

#33 [#32] husky
  .husky/pre-commit
  package.json
  src/app/layout.tsx
  src/components/commons/button/BarButton.tsx
  src/components/commons/modal/index.tsx
  yarn.lock
Labels: 🐛 fix

#15 [#15] Header
  src/app/page.tsx
  src/components/commons/header/Header.tsx
Labels: ✨ feat

#43 [#36] 카드 생성 API 연동
  @types/api/cards.d.ts
  @types/api/commons.d.ts
  src/app/api/cards/postCardImage.ts
  src/app/api/cards/postCreateCard.ts
  src/app/api/createRequestWithToken.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/app/test/card/page.tsx
  src/app/test/input/page.tsx
  src/components/commons/button/index.tsx
  src/components/commons/input/DateInput.tsx
  src/components/commons/input/DropdownInput.tsx
  src/components/commons/input/ImageInput.tsx
  src/components/commons/input/TagInput.tsx
  src/components/commons/input/Textarea.tsx
  src/components/commons/input/index.tsx
  src/components/commons/tag/index.tsx
  src/components/dashboard/CreateCardModal/index.tsx
  src/constants/device.ts
  src/styles/custom-datepicker.css
  src/utils/date.ts
  tsconfig.json
Labels: ✨ feat

#44 [#16] 대시보드 사이드메뉴, 헤더 구현
  src/app/api/dashboards.ts
  src/app/api/users.ts
  src/app/mydashboard/page.tsx
  src/components/commons/circle/ProfileCircle.tsx
  src/components/commons/header/Header.tsx
  src/components/commons/layout/DashboardHeader.tsx
  src/components/commons/layout/Sidemenu.tsx
Labels: ✨ feat

#48 fix: baseUrl 수정
  src/app/api/baseUrl.ts
  src/app/api/createRequestWithToken.ts
  src/constants/globalConstants.ts
  src/utils/cookies.ts
Labels: 🐛 fix

#51 [#39]todo detail UI 구현
  @types/api/auth.d.ts
  @types/api/cards.d.ts
  @types/api/commons.d.ts
  next.config.mjs
  src/app/api/auth.ts
  src/app/api/cards.ts
  src/app/api/createRequestWithToken.ts
  src/app/test/todo-card-test/page.tsx
  src/components/dashboard/CreateCardModal/index.tsx
  src/components/dashboard/todo-detail-card/CardDetails.tsx
  src/components/dashboard/todo-detail-card/CardTitle.tsx
  src/components/dashboard/todo-detail-card/CommentInput.tsx
  src/components/dashboard/todo-detail-card/CommentsList.tsx
  src/components/dashboard/todo-detail-card/DropDownSelectBox.tsx
  src/components/login/LoginForm.tsx
  src/service/authService.ts
  src/store/authStore.ts
  types.ts
Labels: ✨ feat

#54 [#53] 타입 선언 이름 변경 및 위치 경로 수정
  @types/auth.d.ts
  @types/cards.d.ts
  @types/commons.d.ts
  src/app/api/auth.ts
  src/app/api/cards.ts
  src/app/api/cards/postCardImage.ts
  src/app/api/cards/postCreateCard.ts
  src/components/dashboard/CreateCardModal/index.tsx
  src/components/dashboard/todo-detail-card/CardDetails.tsx
  src/components/dashboard/todo-detail-card/CardTitle.tsx
  src/components/login/LoginForm.tsx
  src/components/signup/SignUpForm.tsx
Labels: ♻️ refactor

#55 [#27] 계정관리(mypage) 프로필 부분
  @types/users.ts
  src/app/(dashboard)/layout.tsx
  src/app/(dashboard)/mypage/page.tsx
  src/app/api/users.ts
  src/components/commons/input/ImageInput.tsx
  src/components/commons/layout/DashboardHeader.tsx
  src/components/commons/modal/index.tsx
  src/components/dashboard/CreateCardModal/index.tsx
  src/components/dashboard/todo-detail-card/CardDetails.tsx
  src/components/dashboard/todo-detail-card/CardTitle.tsx
  src/components/dashboard/todo-detail-card/CommentsList.tsx
  src/components/mypage/Profile.tsx
  src/service/authService.ts
  src/store/authStore.ts
Labels: ✨ feat

#56 [#45] 카드 수정 모달
  @types/cards.d.ts
  @types/columns.d.ts
  @types/dashboards.ts
  @types/members.d.ts
  next.config.mjs
  src/app/api/cards-goni.ts
  src/app/api/cards/postCardImage.ts
  src/app/api/cards/postCreateCard.ts
  src/app/api/columns.ts
  src/app/api/members.ts
  src/app/test/card/page.tsx
  src/app/test/todo-card-test/page.tsx
  src/components/commons/circle/ColorCircle.tsx
  src/components/commons/circle/ProfileCircle.tsx
  src/components/commons/input/DateInput.tsx
  src/components/commons/input/DropdownInput.tsx
  src/components/commons/input/TagInput.tsx
  src/components/dashboard/cards/CreateCardModal.tsx
  src/components/dashboard/cards/EditCardModal.tsx
Labels: ✨ feat

#59 [#58] 컬럼 생성, 수정, 삭제
  @types/columns.d.ts
  src/app/api/columns.ts
  src/app/test/column/page.tsx
  src/components/dashboard/columns/ColumnSettingButton.tsx
  src/components/dashboard/columns/CreateColumnModal.tsx
  src/components/dashboard/columns/EditColumnModal.tsx
Labels: ✨ feat

#63 [#38] 계정관리(mypage) 비밀번호 부분
  @types/users.ts
  src/app/(dashboard)/mypage/page.tsx
  src/app/api/users.ts
  src/components/mypage/Password.tsx
  src/utils/validation/schema.ts
Labels: ✨ feat

#66 [#64] 대시보드 관리 - 정보 변경 및 구성원 조회
  @types/dashboard.d.ts
  public/icon/check.svg
  src/app/(dashboard)/edit/[id]/page.tsx
  src/app/api/dashboards.ts
  src/components/dashboard/Edit/DashboardMember.tsx
  src/components/dashboard/Edit/DashboardName.tsx
Labels: ✨ feat

#61 [#40] 대시보드 상세화면 UI 및 API 연동
  @types/cards.d.ts
  @types/dashboard.d.ts
  src/app/api/getCards.ts
  src/app/api/getColumns.ts
  src/app/api/getDashboardId.ts
  src/app/dashboard/[id]/page.tsx
  src/components/commons/button/BarButton.tsx
  src/components/commons/tag/index.tsx
  src/components/dashboard/CreateCardModal/index.tsx
  src/components/dashboard/cards/Card.tsx
  src/components/dashboard/columns/Column.tsx
Labels: ✨ feat
